name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
          package-manager-cache: false

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Rush extract
        run: node common/scripts/install-run-rush.js extract

      - uses: actions/upload-artifact@v4
        with:
          path: dist