name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
          package-manager-cache: false

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js build:prod --verbose

      - name: Rush extract
        run: node common/scripts/install-run-rush.js extract

      - name: Copy resources
        run: |
          # Online installer
          mkdir dist/docs-install/resources
          cp dist/loader/yascml.js dist/docs-install/resources/yascml.js
          cp dist/manager/yascmanager.zip dist/docs-install/resources/yascmanager.zip
          cp dist/api/yascapi.zip dist/docs-install/resources/yascapi.zip

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
  
  docs:
    runs-on: ubuntu-latest
    needs: build
    # TODO: Only deploy when release
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'docs'
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: build-artifact
          path: artifact

      - name: Create pages path
        run: mkdir dist
      
      - name: Copy installer
        run: |
          cp -r artifact/docs-install dist/
          mv dist/docs-install dist/install

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4